
logging:
  level:
    direct-teams: DEBUG
    seda-adapter: DEBUG
    com.example: TRACE
    org.apache.camel: INFO
    org.springframework: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M:%line - %msg%n"

camel:
  dataformat:
    jackson:
      auto-discover-object-mapper: true
  health:
    routesEnabled: true
  springboot:
    health:
      indicator:
        enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

teams:
  card:
    type: MessageCard
    context: http://schema.org/extensions
    themeColor: 0076D7
  webhooks:
    alertMap:
      "[http://localhost:8080/camel/first-alert?httpMethod=post&bridgeEndpoint=true]":
        - high_memory_load
      "[http://localhost:8080/camel/second-alert?httpMethod=post&bridgeEndpoint=true]":
        - yet_another_alert
      "[http://localhost:8080/camel/other-alert?httpMethod=post&bridgeEndpoint=true]":
        - "*"
